import { useEffect, useMemo, useRef, useState } from 'react'
import { Download, FileText, RefreshCw, Search, Upload } from 'lucide-react'
import { api } from '../services/api.js'

const toDataUrl=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})
const fileType=doc=>doc.mime_type?.includes('pdf')?'PDF':doc.file_name?.split('.').pop()?.toUpperCase()||'FILE'
export default function DocsView({ selectedPatient }) {
  const inputRef=useRef(null),user=(()=>{try{return JSON.parse(sessionStorage.getItem('or-smart-user')||'null')}catch{return null}})()
  const [docs,setDocs]=useState([]),[uploading,setUploading]=useState(false),[type,setType]=useState('all'),[round,setRound]=useState('all'),[query,setQuery]=useState('')
  const load=()=>api.getCaseDocuments(selectedPatient.operationNo).then(setDocs).catch(e=>alert(e.message))
  useEffect(()=>{load()},[selectedPatient.operationNo])
  const rounds=useMemo(()=>[...new Set(docs.map(doc=>doc.follow_up_round).filter(Boolean))],[docs])
  const visible=useMemo(()=>docs.filter(doc=>(type==='all'||doc.document_type===type)&&(round==='all'||doc.follow_up_round===round)&&(!query||`${doc.file_name} ${doc.uploaded_by||''} ${selectedPatient.id} ${selectedPatient.name} ${selectedPatient.procedure||''}`.toLowerCase().includes(query.toLowerCase()))),[docs,type,round,query,selectedPatient])
  const upload=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(file.size>5*1024*1024)return alert('ไฟล์ต้องมีขนาดไม่เกิน 5 MB');setUploading(true);try{await api.createCaseDocument(selectedPatient.operationNo,{fileName:file.name,mimeType:file.type||'application/octet-stream',fileSize:file.size,fileData:await toDataUrl(file),documentType:'เอกสารผู้ป่วย',uploadedBy:user?.name,department:user?.department});await load()}catch(e){alert(e.message)}finally{setUploading(false)}}
  const download=async doc=>{try{const data=await api.getCaseDocument(doc.id);const link=document.createElement('a');link.href=data.file_data;link.download=data.file_name;link.click()}catch(e){alert(e.message)}}
  return <div className="mt-2 space-y-4 text-left"><section className="sub-info-card p-6"><h4 className="flex items-center gap-2 text-[16px] font-semibold"><Search size={20} className="text-[#002d73]"/>ค้นหาข้อมูล</h4><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="form-group"><label>ประเภทเอกสาร</label><select className="form-select" value={type} onChange={e=>setType(e.target.value)}><option value="all">ทั้งหมด</option>{[...new Set(docs.map(doc=>doc.document_type).filter(Boolean))].map(value=><option key={value}>{value}</option>)}</select></div><div className="form-group"><label>รอบติดตามเอกสาร</label><select className="form-select" value={round} onChange={e=>setRound(e.target.value)}><option value="all">ทั้งหมด</option>{rounds.map(value=><option key={value}>{value}</option>)}</select></div></div><div className="mt-4 flex flex-wrap items-end gap-3"><div className="form-group min-w-0 flex-1"><label>คำค้นหา</label><input className="form-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหา HN, ชื่อผู้ป่วย, หัตถการ..."/></div><button className="btn-filled-primary inline-flex items-center gap-2"><Search size={15}/>ค้นหา</button><button onClick={()=>{setType('all');setRound('all');setQuery('')}} className="btn-outlined-primary inline-flex items-center gap-2"><RefreshCw size={15}/>ล้างตัวกรอง</button></div></section>
    <section className="sub-info-card overflow-hidden"><header className="flex items-center justify-between border-b border-slate-200 px-6 py-5"><h4 className="text-[16px] font-semibold text-[#002d73]">เอกสารแนบ</h4><input ref={inputRef} type="file" className="hidden" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={upload}/><button disabled={uploading} onClick={()=>inputRef.current?.click()} className="btn-filled-primary inline-flex items-center gap-2 disabled:opacity-50"><Upload size={15}/>{uploading?'กำลังอัปโหลด...':'อัปโหลดเอกสาร'}</button></header><div className="table-responsive"><table className="data-table text-[13px]"><thead><tr><th>ชื่อเอกสาร</th><th>ประเภทไฟล์</th><th>อัปโหลดโดย</th><th>แผนก</th><th>วันที่อัปโหลด</th><th>ขนาด</th><th /></tr></thead><tbody>{!visible.length&&<tr><td colSpan="7" className="py-10 text-center text-slate-400">ยังไม่มีเอกสารที่ตรงกับตัวกรอง</td></tr>}{visible.map(doc=><tr key={doc.id}><td><button onClick={()=>download(doc)} className="inline-flex items-center gap-2 font-medium text-blue-600"><FileText size={18} className="text-red-500"/>{doc.file_name}</button></td><td>{fileType(doc)}</td><td>{doc.uploaded_by||'-'}</td><td>{doc.department||'-'}</td><td>{new Date(doc.created_at).toLocaleString('th-TH')}</td><td>{doc.file_size>=1024*1024?`${(doc.file_size/1024/1024).toFixed(1)} MB`:`${(doc.file_size/1024).toFixed(0)} KB`}</td><td><button onClick={()=>download(doc)} className="text-slate-400 hover:text-blue-600" title="ดาวน์โหลด"><Download size={17}/></button></td></tr>)}</tbody></table></div><footer className="flex items-center justify-between border-t border-slate-200 px-6 py-4 text-[13px] text-slate-500"><span>แสดง {visible.length} จาก {docs.length} รายการ</span><div className="flex gap-2"><button disabled className="rounded border border-slate-200 px-3 py-1.5 disabled:opacity-50">Previous</button><button className="rounded bg-blue-600 px-3 py-1.5 text-white">1</button><button disabled className="rounded border border-slate-200 px-3 py-1.5 disabled:opacity-50">Next</button></div></footer></section></div>
}
