import { useEffect, useMemo, useState } from 'react'
import { Check, ChevronLeft, ChevronRight, Plus, Trash2 } from 'lucide-react'
import { api } from '../services/api.js'

const dateInput = value => { const d = new Date(value); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}` }
const addDays = (base, days) => { const d = new Date(`${base}T12:00:00`); d.setDate(d.getDate() + days - 1); return dateInput(d) }
const templates = { 30: [1, 7, 14, 21, 30], 90: [1, 7, 14, 21, 30, 60, 90] }
function ScheduleCalendar({ rows }) {
  const first = rows.find(row => row.date)?.date || new Date().toISOString().slice(0, 10)
  const [month, setMonth] = useState(() => { const d = new Date(`${first}T00:00:00`); return new Date(d.getFullYear(), d.getMonth(), 1) })
  useEffect(() => { const d = new Date(`${first}T00:00:00`); setMonth(new Date(d.getFullYear(), d.getMonth(), 1)) }, [first])
  const marked = useMemo(() => new Set(rows.map(row => String(row.date || '').slice(0, 10))), [rows])
  const cells = useMemo(() => { const start = new Date(month); start.setDate(1 - start.getDay()); return Array.from({ length: 42 }, (_, i) => { const d = new Date(start); d.setDate(start.getDate() + i); return d }) }, [month])
  return <section className="sub-info-card p-5"><div className="flex items-center justify-between"><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><ChevronLeft size={18} /></button><strong className="text-[14px]">{month.toLocaleDateString('th-TH', { month: 'short', year: 'numeric' })}</strong><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><ChevronRight size={18} /></button></div><div className="mt-5 grid grid-cols-7 gap-y-3 text-center text-[13px]">{['อา','จ','อ','พ','พฤ','ศ','ส'].map(x => <span key={x} className="font-medium text-slate-400">{x}</span>)}{cells.map((d, i) => { const key = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; const active = marked.has(key), muted = d.getMonth() !== month.getMonth(); return <span key={i} className={`mx-auto grid size-8 place-items-center rounded-full ${active ? 'bg-blue-600 font-semibold text-white' : muted ? 'text-slate-300' : 'text-slate-700'}`}>{d.getDate()}</span> })}</div></section>
}

export default function SetupFollowUpView({ selectedPatient, onClose }) {
  const [followUp, setFollowUp] = useState(null), [rows, setRows] = useState([]), [templateDays, setTemplateDays] = useState(30), [autoCalculate, setAutoCalculate] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState('')
  const [configuredSchedules, setConfiguredSchedules] = useState([]), [configuredMethods, setConfiguredMethods] = useState([])
  useEffect(() => { api.getFollowUps(selectedPatient.operationNo).then(items => { const item = items[0]; setFollowUp(item); setRows(item?.schedule || []); setTemplateDays(item?.template_days || 30); setAutoCalculate(item?.auto_calculate !== false) }).catch(e => setError(e.message)) }, [selectedPatient.operationNo])
  useEffect(() => { api.getSettings().then(settings => { setConfiguredSchedules((settings.schedules || []).filter(item => item.enabled !== false)); setConfiguredMethods((settings.methods || []).filter(item => item.name)) }).catch(() => {}) }, [])
  const update = (index, key, value) => setRows(items => items.map((row, i) => i === index ? { ...row, [key]: value } : row))
  const calculateRows = days => { const base = dateInput(selectedPatient.endAt || selectedPatient.startAt || selectedPatient.episodeDate || new Date()); const configuredDays = configuredSchedules.map(item => Number(String(item.day || '').match(/\d+/)?.[0])).filter(day => day && day <= days); return (configuredDays.length ? configuredDays : templates[days]).map(day => ({ id: `day-${day}`, day: `Day ${day}`, date: addDays(base, day), time: '09:00', method: configuredMethods[0]?.name || '', note: '', status: 'PENDING' })) }
  const applyTemplate = days => { setTemplateDays(days); if (autoCalculate) setRows(calculateRows(days)) }
  const save = async () => { setSaving(true); setError(''); try { await api.updateFollowUp(followUp.id, { templateDays, autoCalculate, schedule: rows }); window.dispatchEvent(new Event('operations-updated')); onClose() } catch (e) { setError(e.message) } finally { setSaving(false) } }
  return <div className="mt-2 space-y-4 text-left"><div className="grid gap-5 xl:grid-cols-[320px_minmax(0,1fr)]"><aside className="space-y-5"><section className="sub-info-card p-5"><h4 className="sub-info-card-title">เลือก Template Follow-up</h4><div className="mt-4 space-y-3">{[30,90].map(days => <button key={days} onClick={() => applyTemplate(days)} className={`w-full rounded-xl border p-4 text-left text-[13px] ${templateDays === days ? 'border-blue-500 bg-blue-50/50' : 'border-slate-200'}`}><strong>Follow-up Day {days}</strong><span className="mt-1 block text-[11px] text-slate-500">{templates[days].map(day => `Day ${day}`).join(', ')}</span></button>)}</div></section><ScheduleCalendar rows={rows} /></aside>
    <section className="sub-info-card p-5"><div className="flex items-center justify-between border-b border-slate-100 pb-4"><h4 className="sub-info-card-title">เลือกรอบติดตาม (Follow-up Schedule)</h4><label className="flex items-center gap-2 text-[13px]"><input type="checkbox" checked={autoCalculate} onChange={e => { const checked=e.target.checked; setAutoCalculate(checked); if(checked) setRows(calculateRows(templateDays)) }} />คำนวณวันอัตโนมัติ</label></div><p className="mt-3 text-[12px] text-slate-500">Day 1 เริ่มจากวันที่ออกจากห้องผ่าตัด</p><div className="table-responsive mt-4"><table className="data-table text-[13px]"><thead><tr><th>รอบ <span className="text-red-500">*</span></th><th>วันที่ติดตาม <span className="text-red-500">*</span></th><th>เวลา <span className="text-red-500">*</span></th><th>วิธีติดตาม <span className="text-red-500">*</span></th><th>หมายเหตุ</th><th /></tr></thead><tbody>{rows.map((row,index) => <tr key={row.id || index}><td><input className="form-input min-w-24" value={row.day || ''} onChange={e => update(index,'day',e.target.value)} /></td><td><input type="date" className="form-input min-w-36" value={(row.date || '').slice(0,10)} onChange={e => update(index,'date',e.target.value)} /></td><td><input type="time" className="form-input min-w-28" value={row.time || ''} onChange={e => update(index,'time',e.target.value)} /></td><td><select className="form-select min-w-36" value={row.method || ''} onChange={e => update(index,'method',e.target.value)}><option value="">เลือกวิธี</option><option>โทรศัพท์</option><option>SMS</option><option>พบที่โรงพยาบาล</option></select></td><td><input className="form-input min-w-40" value={row.note || ''} onChange={e => update(index,'note',e.target.value)} /></td><td><button aria-label="ลบรอบ" onClick={() => setRows(items => items.filter((_,i) => i !== index))} className="text-red-500"><Trash2 size={15} /></button></td></tr>)}</tbody></table></div><button onClick={() => setRows(items => [...items,{ id:`manual-${Date.now()}`,day:`รอบที่ ${items.length+1}`,date:'',time:'09:00',method:'',note:'',status:'PENDING'}])} className="btn-outlined-primary mt-4 inline-flex items-center gap-2"><Plus size={14} />เพิ่มรอบติดตาม</button></section></div>
    {error && <p className="text-sm text-red-600">{error}</p>}<div className="flex justify-end gap-3"><button className="btn-outlined-primary" onClick={onClose}>ยกเลิก</button><button disabled={saving || !followUp || !rows.length || rows.some(r => !r.day || !r.date || !r.time || !r.method)} className="btn-filled-primary inline-flex items-center gap-2 disabled:opacity-50" onClick={save}><Check size={15} />{saving ? 'กำลังบันทึก...' : 'บันทึกการแก้ไข Follow-up'}</button></div></div>
}
