import { useCallback, useEffect, useState } from 'react'
import { CheckSquare, Eye, Pencil, X } from 'lucide-react'
import { api } from '../services/api.js'

const dateText = value => value ? new Date(`${String(value).slice(0,10)}T00:00:00`).toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'numeric'}) : '-'
const isDue = value => !value || String(value).slice(0,10) <= new Date().toISOString().slice(0,10)
export default function TimelineView({ selectedPatient, setActiveDetailTab, onSetupFollowUpClick }) {
  const [rows,setRows]=useState([]),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState(null),[editing,setEditing]=useState(false),[result,setResult]=useState(''),[remark,setRemark]=useState(''),[saving,setSaving]=useState(false)
  const load=useCallback(()=>{setLoading(true);return Promise.all([api.getActivities(selectedPatient.operationNo),api.getEvaluations(selectedPatient.operationNo),api.getFollowUps(selectedPatient.operationNo)]).then(([activities,evaluations,followUps])=>{const followUp=followUps[0],byRound=new Map(evaluations.map(item=>[String(item.round_key),item]));const schedule=(followUp?.schedule||[]).map((item,index)=>{const evaluation=byRound.get(String(item.id||item.day));return{id:`round-${item.id||index}`,kind:'round',round:item.day||`รอบที่ ${index+1}`,date:item.date,time:item.time||'-',owner:evaluation?.evaluated_by||followUp.assigned_to||selectedPatient.assignedTo||'-',channel:item.method||'-',detail:item.note||`ติดตามอาการตามรอบติดตามครั้งที่ ${index+1}`,completed:Boolean(evaluation)||item.status==='COMPLETED',current:index===(followUp.current_round_index||0),evaluation}});const inserted=activities.map(item=>({id:`activity-${item.id}`,kind:'activity',round:'กิจกรรมแทรก',date:item.activity_at?.slice(0,10),time:item.activity_at?new Date(item.activity_at).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'}):'-',owner:item.staff||'-',channel:item.activity_type||item.contact_primary||'-',detail:item.detail||item.purpose||'-',completed:new Date(item.activity_at||item.created_at)<=new Date()}));setRows([...schedule,...inserted].sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.time||'').localeCompare(String(b.time||''))))}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[selectedPatient.operationNo,selectedPatient.assignedTo])
  useEffect(()=>{load()},[load])
  const open=(row,edit=false)=>{setSelected(row);setEditing(edit);setResult(row.evaluation?.result||'');setRemark(row.evaluation?.data?.evalRemarks||'')}
  const save=async()=>{setSaving(true);try{await api.updateEvaluation(selected.evaluation.id,{result,data:{...(selected.evaluation.data||{}),evalRemarks:remark},evaluatedBy:selected.evaluation.evaluated_by});setSelected(null);await load();window.dispatchEvent(new Event('operations-updated'))}catch(e){alert(e.message)}finally{setSaving(false)}}
  const visible=filter==='all'?rows:rows.filter(row=>filter==='round'?row.kind==='round':row.kind==='activity')
  return <div className="sub-info-card mt-2 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h4 className="text-[16px] font-medium text-[#002d73]">การติดตาม</h4><div className="grid w-full min-w-0 grid-cols-[minmax(0,1fr)_auto] gap-2 sm:w-auto"><select className="form-select min-w-0 w-full sm:w-36" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">แสดงทั้งหมด</option><option value="round">รอบติดตาม</option><option value="activity">กิจกรรมแทรก</option></select><button className="btn-filled-primary min-w-0 shrink-0 whitespace-nowrap" style={{ padding: '8px 12px', fontSize: '12px' }} onClick={onSetupFollowUpClick}>ตั้งค่ารอบ Follow-up</button></div></div>
    {error&&<p className="mt-5 text-sm text-red-600">{error}</p>}<div className="table-responsive mt-5"><table className="data-table text-[13.5px]"><thead><tr><th>รอบ</th><th>เวลา</th><th>ผู้รับผิดชอบ</th><th>ช่องทางการติดตาม</th><th>รายละเอียด/กิจกรรม</th><th>สถานะติดตาม</th><th>จัดการ</th></tr></thead><tbody>{loading&&<tr><td colSpan="7" className="py-10 text-center text-slate-500">กำลังโหลดข้อมูล...</td></tr>}{!loading&&!visible.length&&<tr><td colSpan="7" className="py-10 text-center text-slate-500">ยังไม่มีข้อมูลการติดตาม</td></tr>}{!loading&&visible.map(row=><tr key={row.id}><td><strong className={row.kind==='activity'?'text-orange-500':'text-blue-600'}>{row.round}</strong><br/><span>{dateText(row.date)}</span></td><td>{row.time}</td><td>{row.owner}</td><td><span className="rounded border border-blue-200 bg-blue-50 px-2 py-1 text-blue-700">{row.channel}</span></td><td>{row.detail}</td><td><span className={`rounded px-2 py-1 ${row.completed?'bg-emerald-50 text-emerald-600':isDue(row.date)?'bg-blue-50 text-blue-600':'bg-slate-100 text-slate-500'}`}>{row.completed?'ประเมินแล้ว':isDue(row.date)?'ถึงกำหนดประเมิน':'รอประเมิน'}</span></td><td>{row.kind==='round'&&row.completed&&row.evaluation?<div className="flex gap-2"><button onClick={()=>open(row)} className="rounded border border-slate-200 p-2 text-blue-600" title="ดูผลประเมิน"><Eye size={15}/></button><button onClick={()=>open(row,true)} className="rounded border border-slate-200 p-2 text-blue-600" title="แก้ไขผลประเมิน"><Pencil size={15}/></button></div>:row.kind==='round'?<button disabled={!row.current||!isDue(row.date)} onClick={()=>setActiveDetailTab('evaluation')} className="inline-flex items-center gap-1 rounded border border-blue-200 px-3 py-2 text-blue-600 disabled:border-slate-200 disabled:text-slate-400"><CheckSquare size={15}/>ประเมินอาการคนไข้</button>:<button onClick={()=>open(row)} className="rounded border border-slate-200 p-2 text-blue-600"><Eye size={15}/></button>}</td></tr>)}</tbody></table></div>
    {selected&&<div className="fixed inset-0 z-[90] grid place-items-center bg-slate-900/50 p-4"><section className="relative w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><button onClick={()=>setSelected(null)} className="absolute right-5 top-5 text-slate-400"><X size={20}/></button><h3 className="text-[18px] font-semibold text-[#002d73]">{editing?'แก้ไขผลการประเมิน':'รายละเอียดการประเมิน'}</h3><div className="mt-5 space-y-4 text-[13px]"><p><span className="text-slate-500">รอบ:</span> {selected.round} ({dateText(selected.date)} {selected.time})</p>{selected.evaluation?<><div className="form-group"><label>ผลการประเมิน <span className="text-red-500">*</span></label><select disabled={!editing} className="form-select" value={result} onChange={e=>setResult(e.target.value)}><option value="not_infected">ไม่เข้าข่ายการติดเชื้อ</option><option value="suspect_ssi">สงสัย SSI</option><option value="confirmed_ssi">ยืนยัน SSI</option></select></div><div className="form-group"><label>การจัดการ/คำแนะนำ</label><textarea disabled={!editing} className="form-input min-h-24" value={remark} onChange={e=>setRemark(e.target.value)}/></div></>:<p>{selected.detail}</p>}</div><div className="mt-6 flex justify-end gap-3"><button className="btn-outlined-primary" onClick={()=>setSelected(null)}>ปิด</button>{editing&&<button disabled={saving||!result} className="btn-filled-primary disabled:opacity-50" onClick={save}>{saving?'กำลังบันทึก...':'บันทึกการแก้ไข'}</button>}</div></section></div>}
  </div>
}
