import { useEffect, useRef, useState } from 'react'
import { Check, Download, Eye, FileText, Paperclip, Send, X } from 'lucide-react'
import { api } from '../services/api.js'

const toDataUrl = file => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file) })
const formatDate = value => value ? new Date(value).toLocaleDateString('th-TH', { day: 'numeric', month: 'short', year: 'numeric' }) : 'ไม่มีข้อมูล'
const departments = ['ศัลยกรรมทั่วไป (General Surgery)', 'ศัลยกรรมกระดูกและข้อ (Orthopedics)', 'ศัลยกรรมประสาท (Neurosurgery)', 'ศัลยกรรมหัวใจและทรวงอก', 'สูติ-นรีเวชกรรม', 'กุมารศัลยกรรม']

export default function TransferCareView({ selectedPatient, setIsTransferCompleted }) {
  const currentType = (selectedPatient.patientType || '').toUpperCase(), targetType = currentType === 'IPD' ? 'OPD' : 'IPD'
  const user = (() => { try { return JSON.parse(sessionStorage.getItem('or-smart-user') || 'null') } catch { return null } })()
  const inputRef = useRef(null)
  const [drawer, setDrawer] = useState(false), [step, setStep] = useState(1), [department, setDepartment] = useState(''), [reason, setReason] = useState(''), [startDate, setStartDate] = useState(''), [notes, setNotes] = useState(''), [file, setFile] = useState(null), [history, setHistory] = useState([]), [docs, setDocs] = useState([]), [saving, setSaving] = useState(false), [historyDetail, setHistoryDetail] = useState(null)
  const load = () => Promise.all([api.getTransfers(selectedPatient.operationNo), api.getCaseDocuments(selectedPatient.operationNo)]).then(([transfers, documents]) => { setHistory(transfers); setDocs(documents) }).catch(e => alert(e.message))
  useEffect(() => { load() }, [selectedPatient.operationNo])
  const latest = history[0]
  const submit = async () => { setSaving(true); try { await api.createTransfer(selectedPatient.operationNo, { toType: targetType, targetDepartment: department, reason, startDate, notes, transferredBy: user?.name }); if (file) await api.createCaseDocument(selectedPatient.operationNo, { fileName: file.name, mimeType: file.type || 'application/octet-stream', fileSize: file.size, fileData: await toDataUrl(file), documentType: 'เอกสารแนบการส่งต่อ', uploadedBy: user?.name, department: user?.department }); setDrawer(false); setIsTransferCompleted(true); await load(); window.dispatchEvent(new Event('operations-updated')) } catch (e) { alert(e.message) } finally { setSaving(false) } }
  const download = async doc => { try { const data = await api.getCaseDocument(doc.id); const link = document.createElement('a'); link.href = data.file_data; link.download = data.file_name; link.click() } catch (e) { alert(e.message) } }
  const canNext = department && reason && startDate
  return <div className="mt-2 space-y-4 text-left">
    {latest && <div className="flex items-center gap-4 rounded-xl border border-emerald-200 bg-emerald-50 px-7 py-6 text-emerald-700"><span className="grid size-12 shrink-0 place-items-center rounded-full bg-emerald-500 text-white shadow"><Check size={25} strokeWidth={3}/></span><div><h3 className="text-[20px] font-semibold">ส่งต่อเคสสำเร็จ</h3><p className="mt-1 text-[14px]">ระบบได้ส่งเคสไปยังแผนก {latest.to_type} เรียบร้อยแล้ว</p></div></div>}
    <section className="sub-info-card overflow-hidden"><h4 className="border-b border-slate-200 px-6 py-5 text-[16px] font-medium text-[#002d73]">ข้อมูลการส่งต่อปัจจุบัน</h4><div className="grid gap-5 bg-slate-50/70 px-6 py-5 md:grid-cols-4">{[['วันที่ส่งต่อ',latest ? formatDate(latest.created_at) : 'ไม่มีข้อมูล'],['เหตุผลการส่งต่อ',latest?.reason || 'ไม่มีข้อมูล'],['วันที่เริ่มติดตามโดยแผนกรับ',latest ? formatDate(latest.start_date) : 'ไม่มีข้อมูล'],['สถานะการส่งต่อ',latest ? `รอ ${latest.to_type} รับเคส` : 'ไม่มีข้อมูล']].map(([label,value]) => <div key={label}><p className="text-[12px] text-slate-500">{label}</p><p className="mt-1 text-[13px] font-medium text-slate-700">{value}</p></div>)}</div></section>
    <section className="sub-info-card overflow-hidden"><h4 className="border-b border-slate-200 px-6 py-5 text-[16px] font-medium text-[#002d73]">เอกสารแนบ (ถ้ามี)</h4>{docs.length ? <div className="space-y-2 p-5">{docs.map(doc => <div key={doc.id} className="flex items-center gap-3 rounded-lg border border-slate-100 bg-slate-50 px-4 py-3"><FileText size={18} className="text-blue-600" /><span className="flex-1 text-[13px]">{doc.file_name}</span><button onClick={() => download(doc)} className="text-slate-400 hover:text-blue-600" title="ดาวน์โหลด"><Download size={17}/></button></div>)}</div> : <div className="bg-slate-50/70 py-8 text-center text-[13px] text-slate-400">ไม่มีข้อมูล</div>}</section>
    {!latest && <div className="rounded-lg border border-orange-200 bg-orange-50 px-5 py-4 text-[13px] text-orange-700">ยังไม่ได้ส่งไปยังแผนก {targetType} กรุณาตรวจสอบข้อมูลก่อนยืนยันการส่งต่อ</div>}
    {!latest && <div className="flex justify-end rounded-xl border border-slate-200 bg-white p-4"><button onClick={() => { setStep(1); setDrawer(true) }} className="btn-filled-primary inline-flex items-center gap-2"><Send size={16} />ย้ายเคส / ส่งต่อการดูแล</button></div>}
    {history.length > 0 && <section className="sub-info-card p-5"><h4 className="sub-info-card-title mb-4">ประวัติการส่งต่อ</h4><div className="table-responsive"><table className="data-table text-[13px]"><thead><tr><th>วันที่/เวลา</th><th>จาก</th><th>ไป</th><th>แผนกปลายทาง</th><th>ผู้ส่ง</th><th>เหตุผล</th><th>ดู</th></tr></thead><tbody>{history.map(row => <tr key={row.id}><td>{new Date(row.created_at).toLocaleString('th-TH')}</td><td>{row.from_type}</td><td>{row.to_type}</td><td>{row.target_department}</td><td>{row.transferred_by || '-'}</td><td>{row.reason}</td><td><button onClick={() => setHistoryDetail(row)} className="rounded border border-slate-200 p-2 text-blue-600" title="ดูประวัติ"><Eye size={15}/></button></td></tr>)}</tbody></table></div></section>}
    {latest && <div className="flex justify-end gap-3 rounded-xl border border-slate-200 bg-white p-4"><button onClick={() => window.history.back()} className="btn-outlined-primary">กลับไปหน้ารายการเคส</button><button onClick={() => setHistoryDetail(latest)} className="btn-filled-primary">ดูประวัติการดำเนินการ</button></div>}
    {historyDetail && <div className="fixed inset-0 z-[90] grid place-items-center bg-slate-900/50 p-4"><section className="relative max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><button onClick={() => setHistoryDetail(null)} className="absolute right-5 top-5 text-slate-400"><X size={21}/></button><h3 className="text-[19px] font-semibold text-[#002d73]">ประวัติการย้ายเคส</h3><h4 className="mt-6 border-b border-slate-200 pb-3 text-[15px] font-semibold">ข้อมูลผู้ป่วย</h4><div className="mt-4 grid gap-3 text-[13px] sm:grid-cols-2">{[['HN',selectedPatient.id],['ชื่อ-สกุล',selectedPatient.name],['หัตถการ',selectedPatient.procedure||'-'],['วันที่ผ่าตัด',selectedPatient.surgeryDate||'-'],['ศัลยแพทย์',selectedPatient.surgeon||'-'],['สถานะ SSI',selectedPatient.ssiStatus||'-']].map(([a,b])=><p key={a} className="flex justify-between gap-4"><span className="text-slate-500">{a}</span><strong className="text-right">{b}</strong></p>)}</div><h4 className="mt-6 border-b border-slate-200 pb-3 text-[15px] font-semibold">ข้อมูลการส่งต่อ</h4><div className="mt-4 space-y-3 text-[13px]">{[['วันที่/เวลา',new Date(historyDetail.created_at).toLocaleString('th-TH')],['ต้นทาง',historyDetail.from_type],['ปลายทาง',historyDetail.to_type],['แผนกปลายทาง',historyDetail.target_department],['วันที่เริ่มติดตาม',formatDate(historyDetail.start_date)],['ผู้ส่งต่อ',historyDetail.transferred_by||'-'],['เหตุผลการส่งต่อ',historyDetail.reason],['หมายเหตุเพิ่มเติม',historyDetail.notes||'-']].map(([a,b])=><p key={a} className="flex justify-between gap-6 border-b border-slate-100 pb-2"><span className="text-slate-500">{a}</span><strong className="text-right">{b}</strong></p>)}</div>{docs.length>0&&<><h4 className="mt-6 border-b border-slate-200 pb-3 text-[15px] font-semibold">เอกสารแนบ</h4><div className="mt-3 space-y-2">{docs.map(doc=><button key={doc.id} onClick={()=>download(doc)} className="flex w-full items-center gap-3 rounded-lg bg-slate-50 p-3 text-left text-[13px]"><FileText size={17} className="text-blue-600"/><span className="flex-1">{doc.file_name}</span><Download size={16} className="text-slate-400"/></button>)}</div></>}<div className="mt-6 flex justify-end"><button onClick={() => setHistoryDetail(null)} className="btn-filled-primary">ปิด</button></div></section></div>}
    {drawer && <div className="drawer-overlay" onClick={() => setDrawer(false)}><aside className="side-drawer" onClick={e => e.stopPropagation()}><header className="drawer-header"><h3 className="text-[18px] font-semibold">ย้ายเคส / ส่งต่อการดูแล</h3><button onClick={() => setDrawer(false)} className="text-slate-400"><X size={22} /></button></header><div className="drawer-content">
      <div className="mb-7 flex items-start justify-center"><div className="text-center"><span className="mx-auto grid size-9 place-items-center rounded-full bg-blue-600 text-white">{step > 1 ? <Check size={16}/> : '1'}</span><small className="mt-2 block text-blue-600">ระบุข้อมูลการส่งต่อ</small></div><div className="mt-4 h-px w-24 bg-slate-200"/><div className="text-center"><span className={`mx-auto grid size-9 place-items-center rounded-full ${step === 2 ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-400'}`}>2</span><small className="mt-2 block text-slate-400">ตรวจสอบข้อมูล</small></div></div>
      <h4 className="mb-4 text-[14px] font-semibold text-[#002d73]">ข้อมูลผู้ป่วย</h4><div className="space-y-3 border-b border-slate-200 pb-6 text-[13px]">{[['HN',selectedPatient.id],['ชื่อ-สกุล',selectedPatient.name],['วันที่ผ่าตัด',selectedPatient.surgeryDate || '-']].map(([a,b]) => <p key={a} className="flex justify-between"><span className="text-slate-500">{a}</span><strong>{b}</strong></p>)}</div>
      {step === 1 ? <div className="mt-6 space-y-4"><h4 className="text-[16px] font-semibold">ข้อมูลการส่งต่อ</h4><div className="form-group"><label>แผนกปัจจุบัน (ผู้ส่งต่อ)</label><input className="form-input" value={`${currentType} - ${selectedPatient.receivingDepartment || user?.department || '-'}`} readOnly /></div><div className="form-group"><label>ส่งต่อไปยังแผนก <span className="text-red-500">*</span></label><select className="form-select" value={department} onChange={e => setDepartment(e.target.value)}><option value="">เลือกแผนก {targetType}</option>{departments.map(x => <option key={x}>{x}</option>)}</select><p className="mt-1 text-[11px] text-slate-400">ปลายทาง: {targetType}</p></div><div className="form-group"><label>เหตุผลการส่งต่อ <span className="text-red-500">*</span></label><select className="form-select" value={reason} onChange={e => setReason(e.target.value)}><option value="">เลือกเหตุผล</option><option>จำหน่ายจากโรงพยาบาลเพื่อติดตามต่อ</option><option>รับไว้รักษาในโรงพยาบาล</option><option>เปลี่ยนแผนกผู้รับผิดชอบ</option><option>อื่นๆ</option></select></div><div className="form-group"><label>วันที่เริ่มติดตามโดยแผนกรับ <span className="text-red-500">*</span></label><input type="date" className="form-input" value={startDate} onChange={e => setStartDate(e.target.value)} /></div><div className="form-group"><label>หมายเหตุเพิ่มเติม</label><textarea className="form-input min-h-24" value={notes} onChange={e => setNotes(e.target.value)} /></div><div className="form-group"><label>แนบเอกสาร (ถ้ามี)</label><input ref={inputRef} type="file" className="hidden" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={e => { const next=e.target.files?.[0]; if(next?.size>5*1024*1024){alert('ไฟล์ต้องไม่เกิน 5 MB');e.target.value='';return} setFile(next||null) }} /><button onClick={() => inputRef.current?.click()} className="btn-outlined-primary inline-flex items-center gap-2"><Paperclip size={15}/>แนบไฟล์</button>{file && <p className="mt-2 text-[12px] text-slate-600">{file.name} • {(file.size/1024).toFixed(1)} KB</p>}</div></div> : <div className="mt-6 space-y-4"><h4 className="text-[16px] font-semibold">ตรวจสอบข้อมูลก่อนส่ง</h4>{[['ต้นทาง',currentType],['ปลายทาง',targetType],['แผนกปลายทาง',department],['เหตุผล',reason],['วันที่เริ่มติดตาม',formatDate(startDate)],['หมายเหตุ',notes || '-'],['เอกสารแนบ',file?.name || 'ไม่มี']].map(([a,b]) => <div key={a} className="flex justify-between gap-6 border-b border-slate-100 py-2 text-[13px]"><span className="text-slate-500">{a}</span><strong className="text-right">{b}</strong></div>)}</div>}
    </div><footer className="flex gap-3 border-t border-slate-200 p-5"><button onClick={() => step === 1 ? setDrawer(false) : setStep(1)} className="btn-outlined-primary">{step === 1 ? 'ยกเลิก' : 'ย้อนกลับ'}</button><button disabled={!canNext || saving} onClick={() => step === 1 ? setStep(2) : submit()} className="btn-filled-primary flex-1 disabled:opacity-50">{step === 1 ? 'ถัดไป' : saving ? 'กำลังส่ง...' : `ยืนยันส่งไป ${targetType}`}</button></footer></aside></div>}
  </div>
}
