CREATE TABLE IF NOT EXISTS ris_operations (
    id SERIAL PRIMARY KEY,

    request_id UUID NOT NULL UNIQUE,
    event_type VARCHAR(50) NOT NULL,
    source_system VARCHAR(100) NOT NULL,

    hn VARCHAR(50) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    date_of_birth DATE,
    age INTEGER,
    sex VARCHAR(30),
    height_cm NUMERIC(6,2),
    weight_kg NUMERIC(6,2),
    bmi NUMERIC(6,2),
    patient_photo TEXT,

    episode_no VARCHAR(100) NOT NULL,
    episode_date DATE,
    ward_name VARCHAR(100),
    bed_no VARCHAR(50),
    patient_type VARCHAR(10),
    receiving_department VARCHAR(255),
    or_handover_note TEXT,

    operation_no VARCHAR(100) NOT NULL UNIQUE,
    surgeon VARCHAR(255),
    second_surgeon VARCHAR(255),
    third_surgeon VARCHAR(255),
    anesthesiologist VARCHAR(255),
    anesthesia_type VARCHAR(100),
    special_equipment TEXT,
    scrub_nurse VARCHAR(255),
    circulating_nurse VARCHAR(255),
    anesthesia_nurse VARCHAR(255),
    operation_department VARCHAR(255),
    operation_location VARCHAR(255),
    operating_room VARCHAR(100),
    urgency VARCHAR(50),
    operation_type VARCHAR(50),
    preoperative_diagnosis TEXT,
    procedure_name TEXT NOT NULL,
    procedure_free_text TEXT,
    primary_body_site VARCHAR(100),
    laterality VARCHAR(50),
    secondary_operation TEXT,
    start_at TIMESTAMPTZ,
    end_at TIMESTAMPTZ,
    duration_minutes INTEGER,
    outcome VARCHAR(100),
    report_template TEXT,
    status VARCHAR(50),
    implant_present BOOLEAN,
    implant VARCHAR(255),
    wound_class VARCHAR(100),
    comorbidities TEXT,
    smoking_status VARCHAR(30),
    wound_at_discharge VARCHAR(100),
    wound_discharge_notes TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
