import { Bell, Database, Save, ShieldCheck, SlidersHorizontal } from 'lucide-react'
import { useState } from 'react'
import PageHeader from '../components/ui/PageHeader.jsx'

const tabs = [{ label: 'การตั้งค่าทั่วไป', icon: SlidersHorizontal }, { label: 'การแจ้งเตือน', icon: Bell }, { label: 'สิทธิ์และความปลอดภัย', icon: ShieldCheck }, { label: 'การเชื่อมต่อ HIS', icon: Database }]

export default function SettingsPage() {
  const [tab, setTab] = useState(0)
  return <><PageHeader title="ตั้งค่าระบบ" description="กำหนดค่าการทำงานให้เหมาะสมกับนโยบายขององค์กร" actions={<button className="btn-primary"><Save size={14} />บันทึกการตั้งค่า</button>} /><div className="grid gap-4 lg:grid-cols-[230px_1fr]"><aside className="card h-fit p-2">{tabs.map(({label,icon:Icon}, index) => <button key={label} onClick={() => setTab(index)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-xs ${tab === index ? 'bg-blue-50 font-semibold text-blue-700' : 'text-slate-500 hover:bg-slate-50'}`}><Icon size={16} />{label}</button>)}</aside><section className="card"><div className="card-title"><div><h2>{tabs[tab].label}</h2><p>ตั้งค่าและนโยบายการทำงานของระบบ</p></div></div><div className="mt-5 space-y-5"><label className="form-label">ชื่อหน่วยงาน<input className="field mt-2" defaultValue="โรงพยาบาลกรุงเทพ เชียงใหม่" /></label><div className="grid gap-4 md:grid-cols-2"><label className="form-label">จำนวนวันติดตามเริ่มต้น<select className="field mt-2"><option>30 วัน</option><option>60 วัน</option><option>90 วัน</option></select></label><label className="form-label">Timezone<select className="field mt-2"><option>Asia/Bangkok (UTC+7)</option></select></label></div><div className="border-t border-slate-100 pt-5"><h3 className="text-sm font-semibold text-slate-700">Workflow และการแจ้งเตือน</h3><div className="mt-3 divide-y divide-slate-100">{['แจ้งเตือนเมื่อเคสติดตามเกินกำหนด', 'ส่งเคสความเสี่ยงสูงให้แพทย์อัตโนมัติ', 'อนุญาตให้หน่วยงานเห็นข้อมูลข้ามแผนก', 'บันทึก Audit log ทุกการเปลี่ยนแปลง'].map((label, index) => <label key={label} className="flex items-center justify-between py-3 text-xs text-slate-600"><span>{label}</span><input type="checkbox" defaultChecked={index !== 2} className="h-4 w-4 accent-blue-600" /></label>)}</div></div><div className="rounded-lg border border-blue-100 bg-blue-50 p-4 text-xs leading-6 text-blue-700"><strong>หมายเหตุด้านองค์กร:</strong> การเปลี่ยนแปลงสิทธิ์ผู้ใช้, SLA และการเชื่อมต่อ HIS ควรผ่านการอนุมัติของ System Owner และบันทึกใน Audit log</div></div></section></div></>
}
