import { Download, Plus, UserCog } from 'lucide-react'
import { useState } from 'react'
import Filters from '../components/ui/Filters.jsx'
import MetricCard from '../components/ui/MetricCard.jsx'
import PageHeader from '../components/ui/PageHeader.jsx'
import StatusBadge from '../components/ui/StatusBadge.jsx'
import { users } from '../data/mockData.js'

export default function UserManagementPage() { const [search, setSearch] = useState(''); const data = users.filter((item) => [item.name,item.email,item.department].some((x) => x.toLowerCase().includes(search.toLowerCase()))); return <><PageHeader title="จัดการผู้ใช้งาน" description="กำหนดบัญชี บทบาท และสิทธิ์ตามโครงสร้างองค์กร" actions={<><button className="btn-secondary"><Download size={14} />ส่งออก</button><button className="btn-primary"><Plus size={14} />เพิ่มผู้ใช้งาน</button></>} /><section className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><MetricCard label="ผู้ใช้ทั้งหมด" value="156" unit="บัญชี" trend="+8%" /><MetricCard label="ใช้งานอยู่" value="142" unit="บัญชี" trend="+4%" tone="green" /><MetricCard label="รออนุมัติ" value="14" unit="บัญชี" trend="+2" tone="amber" /><MetricCard label="บทบาท" value="7" unit="ประเภท" trend="+1" tone="violet" /></section><Filters search={search} onSearch={setSearch} compact /><section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-xs"><thead className="bg-slate-50 text-[10px] text-slate-500 uppercase"><tr><th className="table-cell">ผู้ใช้งาน</th><th className="table-cell">บทบาท</th><th className="table-cell">หน่วยงาน</th><th className="table-cell">อีเมล</th><th className="table-cell">สถานะ</th><th className="table-cell"></th></tr></thead><tbody>{data.map((user) => <tr key={user.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="table-cell font-semibold text-slate-700">{user.name}</td><td className="table-cell">{user.role}</td><td className="table-cell">{user.department}</td><td className="table-cell text-slate-500">{user.email}</td><td className="table-cell"><StatusBadge>{user.status}</StatusBadge></td><td className="table-cell"><button className="rounded-lg p-2 text-blue-600 hover:bg-blue-50"><UserCog size={16} /></button></td></tr>)}</tbody></table></div></section></> }
