import { AlertTriangle, CalendarClock, CheckCircle2, PhoneCall, RefreshCw, Search, UserRound, XCircle } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useApiQuery } from '../hooks/useApiQuery.js'
import { api } from '../services/api.js'

const keyOf=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
const todayKey=keyOf(new Date())
const roundColors=['#3b82f6','#10b981','#f97316','#4338ca','#d946ef','#f59e0b','#8b5cf6','#ef4444']
export default function CalendarPage(){
  const {data:patients,loading,error}=useApiQuery(api.getFollowUpPatients)
  const [month,setMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)}),[selectedDate,setSelectedDate]=useState(todayKey),[department,setDepartment]=useState('all'),[procedure,setProcedure]=useState('all'),[roundFilter,setRoundFilter]=useState('all'),[risk,setRisk]=useState('all'),[status,setStatus]=useState('all'),[query,setQuery]=useState('')
  const departments=useMemo(()=>[...new Set(patients.map(p=>p.receivingDepartment||p.department).filter(Boolean))],[patients]),procedures=useMemo(()=>[...new Set(patients.map(p=>p.procedure).filter(Boolean))],[patients])
  const tasks=useMemo(()=>patients.flatMap(patient=>(patient.followUpSchedule||[]).map((round,index)=>({...round,date:String(round.date||round.scheduledAt||'').slice(0,10),patient,index,completed:round.status==='COMPLETED'}))).filter(task=>task.date).filter(task=>(department==='all'||(task.patient.receivingDepartment||task.patient.department)===department)&&(procedure==='all'||task.patient.procedure===procedure)&&(roundFilter==='all'||String(task.day||`รอบที่ ${task.index+1}`)===roundFilter)&&(risk==='all'||task.patient.ssiStatus===risk)&&(status==='all'||(status==='completed'?task.completed:status==='overdue'?!task.completed&&task.date<todayKey:!task.completed))&&(!query||`${task.patient.id} ${task.patient.name} ${task.patient.procedure}`.toLowerCase().includes(query.toLowerCase()))),[patients,department,procedure,roundFilter,risk,status,query])
  const byDate=useMemo(()=>tasks.reduce((map,task)=>(map.set(task.date,[...(map.get(task.date)||[]),task]),map),new Map()),[tasks]),selectedTasks=byDate.get(selectedDate)||[]
  const allRaw=useMemo(()=>patients.flatMap(p=>(p.followUpSchedule||[]).map((r,i)=>({...r,date:String(r.date||r.scheduledAt||'').slice(0,10),patient:p,index:i,completed:r.status==='COMPLETED'}))).filter(x=>x.date),[patients])
  const metrics=[['ครบกำหนดวันนี้',allRaw.filter(x=>x.date===todayKey&&!x.completed).length,'ต้องรับเคสวันนี้',CalendarClock,'#1e3a8a','#dbeafe'],['นัดหมายแล้ววันนี้',allRaw.filter(x=>x.date===todayKey).length,'ต้องติดตามวันนี้',PhoneCall,'#8b5cf6','#ede9fe'],['ติดต่อไม่สำเร็จ',patients.filter(p=>p.evaluationData?.contactStatus==='failed').length,'คนไข้ไม่รับโทรศัพท์',PhoneCall,'#f97316','#ffedd5'],['ดำเนินการเสร็จ',allRaw.filter(x=>x.completed).length,'ติดตามเสร็จสิ้น',CheckCircle2,'#10b981','#ecfdf5'],['เกินกำหนด',allRaw.filter(x=>!x.completed&&x.date<todayKey).length,'เกินกำหนดแล้ว',XCircle,'#ef4444','#fef2f2'],['สงสัย SSI',patients.filter(p=>p.ssiStatus==='SUSPECTED_SSI').length,'เคสรอแพทย์ตรวจสอบ',AlertTriangle,'#ea580c','#fff7ed'],['รอผู้ป่วยตอบกลับ',allRaw.filter(x=>!x.completed&&x.date===todayKey).length,'ต้องติดตามวันนี้',UserRound,'#0f9f8f','#ccfbf1']]
  const year=month.getFullYear(),mi=month.getMonth(),first=new Date(year,mi,1),start=new Date(year,mi,1-first.getDay()),cells=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return{date:d,key:keyOf(d),outside:d.getMonth()!==mi}})
  const clear=()=>{setDepartment('all');setProcedure('all');setRoundFilter('all');setRisk('all');setStatus('all');setQuery('')}
  return <div className="space-y-5">{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error.message}</div>}
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">{metrics.map(([label,value,detail,Icon,color,bg])=><article key={label} className="min-h-32 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between"><p className="text-[13px] font-medium" style={{color}}>{label}</p><span className="grid size-9 place-items-center rounded-lg" style={{color,background:bg}}><Icon size={19}/></span></div><p className="mt-3 text-[28px] font-semibold" style={{color}}>{value} <small className="text-[13px]">คน</small></p><p className="text-[11px] text-slate-500">{detail}</p></article>)}</section>
    <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="flex items-center gap-2 text-[16px] font-semibold"><Search size={19} className="text-[#002d73]"/>ค้นหาข้อมูล</h2><div className="mt-5 grid gap-3 md:grid-cols-4"><label className="text-[12px]">แผนก<select className="form-select mt-1" value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">ทั้งหมด</option>{departments.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-[12px]">หัตถการ<select className="form-select mt-1" value={procedure} onChange={e=>setProcedure(e.target.value)}><option value="all">ทั้งหมด</option>{procedures.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-[12px]">รอบการติดตาม<select className="form-select mt-1" value={roundFilter} onChange={e=>setRoundFilter(e.target.value)}><option value="all">ทั้งหมด</option>{[...new Set(allRaw.map(x=>String(x.day||`รอบที่ ${x.index+1}`)))].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-[12px]">ระดับความเสี่ยง<select className="form-select mt-1" value={risk} onChange={e=>setRisk(e.target.value)}><option value="all">ทั้งหมด</option><option value="UNASSESSED">ยังไม่ประเมิน</option><option value="NOT_SSI">ไม่เข้าข่าย SSI</option><option value="SUSPECTED_SSI">สงสัย SSI</option><option value="CONFIRMED_SSI">ยืนยัน SSI</option></select></label></div><div className="mt-3 flex flex-wrap items-end gap-3"><label className="min-w-40 text-[12px]">สถานะ<select className="form-select mt-1" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">ทั้งหมด</option><option value="pending">รอดำเนินการ</option><option value="completed">เสร็จสิ้น</option><option value="overdue">เกินกำหนด</option></select></label><label className="min-w-0 flex-1 text-[12px]">คำค้นหา<input className="form-input mt-1" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหา HN, ชื่อผู้ป่วย, หัตถการ..."/></label><button className="btn-filled-primary inline-flex items-center gap-2"><Search size={15}/>ค้นหา</button><button onClick={clear} className="btn-outlined-primary inline-flex items-center gap-2"><RefreshCw size={15}/>ล้างตัวกรอง</button></div></section>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_350px]"><section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center justify-between px-5 py-4"><button onClick={()=>setMonth(new Date(year,mi-1,1))} className="px-3 text-xl text-slate-400">‹</button><h2 className="font-semibold">{month.toLocaleDateString('th-TH',{month:'long',year:'numeric'})}</h2><button onClick={()=>setMonth(new Date(year,mi+1,1))} className="px-3 text-xl text-slate-400">›</button></header><div className="grid grid-cols-7 border-l border-t border-slate-200">{['อา.','จ.','อ.','พ.','พฤ.','ศ.','ส.'].map(x=><div key={x} className="border-b border-r bg-slate-50 py-3 text-center text-[12px] font-medium text-slate-500">{x}</div>)}{cells.map(cell=>{const items=byDate.get(cell.key)||[];return <button key={cell.key} onClick={()=>setSelectedDate(cell.key)} className={`min-h-24 border-b border-r p-2 text-left ${cell.outside?'bg-slate-50 text-slate-300':'text-slate-700'} ${selectedDate===cell.key?'ring-2 ring-inset ring-blue-500':''}`}><span className="text-[12px]">{cell.date.getDate()}</span>{items.length>0&&<><span className={`mt-5 block rounded px-2 py-1 text-center text-[11px] font-medium ${items.every(x=>x.completed)?'bg-emerald-50 text-emerald-600':'bg-blue-50 text-blue-600'}`}>{items.length} ราย</span><span className="mt-1 flex justify-center gap-1">{[...new Set(items.map(x=>x.index))].slice(0,5).map(i=><i key={i} className="size-1.5 rounded-full" style={{background:roundColors[i%roundColors.length]}}/>)}</span></>}</button>})}</div><footer className="flex flex-wrap gap-4 p-4 text-[11px]">{['Day 1','Day 7','Day 14','Day 21','Day 28','Day 30','Day 60','Day 90'].map((x,i)=><span key={x} className="inline-flex items-center gap-1"><i className="size-2 rounded-full" style={{background:roundColors[i]}}/>{x}</span>)}</footer></section>
      <aside className="flex max-h-[720px] flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center justify-between border-b border-slate-200 p-4"><h3 className="block-section-title">รายการงานวันนี้ <small className="font-normal text-slate-500">({new Date(`${selectedDate}T12:00:00`).toLocaleDateString('th-TH')})</small></h3><span className="rounded bg-blue-50 px-2 py-1 text-[11px] text-blue-600">{selectedTasks.length} เคส</span></header><div className="flex-1 space-y-3 overflow-y-auto p-3">{loading&&<p className="py-10 text-center text-sm text-slate-400">กำลังโหลด...</p>}{!loading&&!selectedTasks.length&&<p className="py-10 text-center text-sm text-slate-400">ไม่มีงานติดตามในวันนี้</p>}{selectedTasks.map(task=><article key={`${task.patient.operationNo}-${task.index}`} className={`rounded-lg border p-3 ${task.completed?'border-emerald-200 bg-emerald-50/60':'border-blue-200 bg-blue-50/60'}`}><div className="flex justify-between gap-2"><strong className="text-[13px]">{task.patient.name} <small className="font-normal text-slate-500">HN{task.patient.id}</small></strong><span className="text-[11px] text-blue-600">รอบ {task.index+1}/{task.patient.followUpSchedule.length}</span></div><p className="mt-1 text-[12px] font-medium text-blue-700">{task.date} | {task.time||'-'}</p><p className="mt-1 text-[11px] text-slate-600">{task.day||`รอบที่ ${task.index+1}`} | {task.method||'-'}</p><p className="mt-1 text-[11px] text-slate-500">ผู้รับผิดชอบ: {task.patient.assignedTo||'-'}</p><Link to={`/follow-ups/${task.patient.id}`} className="mt-3 block rounded bg-blue-600 px-3 py-1.5 text-center text-[11px] text-white">{task.completed?'ดูผลการติดตาม':'เริ่มติดตาม'}</Link></article>)}</div></aside></div>
  </div>
}
